language: go

# You don't need to test on very old version of the Go compiler. It's the user's
# responsibility to keep their compilers up to date.
go:
  - 1.11.x

os:
  - linux
  - osx
  - windows

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

gobuild_args: -x -ldflags "-X github.com/valasek/timesheet/version.Version=0.0.8"

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test

deploy:
  prerelease: true
  provider: releases
  api_key:
    secure: myWlnTneS5WzgIA7V0qA7tcGw6bvgQsQ0F4UNml4Gxh1stegAY6qZZdH6sFpu2RC6bD99P7lFHaBV3WSiWo5JHjCqsCrdEbfIZa1auydy8QMBWH8O5hnjdRrYuQTSd3kbjp4XxJlItI/41bdt8fWANHRrycSzyECpewSkQ5cWuX8FBUF4hxUyBFA0vT52upxk115vJ8CqwVa5M+9stZvLfgeNK0bFA9t6nEheNtKV3ZF9CagSGKBCXO8QvVz6PVzbZwAG/8drvJzt+5u3EJ4aPUJqWHabvH/fQ0AT9C4XD851R+X23eT3QgACjHOQTHgrlXcGhje9lJTdwxNL6U9AzSM4lXkrRifz//FGqtu6nNyz11er5goSRscFyxzL5E/e0VmDi0XEZoC6dUU5xOscJsw9JXAEk7oSXLF+QMZ8dl0UZIHUCeTsUsXDWipBIsK1ZLoj8pmYgfZDM8MQYFzvQlXVpMlAw7cU4OA8KbxdJ4jWizkq/xBmCC+cinCcm85ndvIRJFOhb/CCl0dkxLH64VlA+GUNJgEMIF6co0LLJFSstJLoh0J4MnXKiHroqY/C+vtguKKDz+QtFgIgbVmdKRTSSGRMwQggyyJqo699DiMkRq7FzfGFY/marCRQO8g1zANPt17cn9Tiuswtb9EBgjwqY4xAAnss5N4idvgFx0=
  file:
    - timesheet.exe
    - timesheet.bin
    - timesheet.app
    # - directory/*
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    repo: valasek/timesheet